# Generated by Django 2.2.7 on 2020-03-03 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('date_added', models.DateField(default=datetime.datetime.now)),
                ('slug', models.CharField(max_length=500)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
